language: android
jdk: oraclejdk7
branches:
  only:
    - master
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # minutes (2 minutes by default)
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

    - extra-android-m2repository

    - sys-img-armeabi-v7a-android-21

  licenses:
    - 'android-sdk-license-.+'

before_install:
    - chmod +x gradlew