language: android
branches:
  only:
    - master
android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23

    - extra-android-m2repository

    - sys-img-x86-android-23

before_install:
    - chmod +x gradlew